# Generated by Django 4.0.2 on 2022-03-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_name_delete_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
