# Generated by Django 3.2.11 on 2022-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
