# Generated by Django 3.2.11 on 2022-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220314_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper.png', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.CharField(blank=True, default='https://webgrowhub.com/wp-content/uploads/2020/12/photo-1552566626-52f8b828add9.jpg', max_length=8000, null=True),
        ),
    ]
