# Generated by Django 4.0.2 on 2022-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_images_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=8000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='vedio',
            field=models.ManyToManyField(to='recipes.Vedio'),
        ),
    ]
