# Generated by Django 4.0.2 on 2022-02-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_vedio_recipe_vedio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='vedio',
        ),
    ]
