# Generated by Django 4.0.2 on 2022-02-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_vedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vedio',
            field=models.ManyToManyField(to='recipes.Vedio'),
        ),
    ]
