# Generated by Django 4.0.2 on 2022-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Instruction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vedio',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Vedio'),
        ),
    ]
