# Generated by Django 4.0.2 on 2022-02-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_images_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='vedio',
            new_name='vedios',
        ),
    ]
