# Generated by Django 4.0.2 on 2022-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_vedio_recipe_vedios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(to='recipes.Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='recipes.Instruction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vedios',
            field=models.ManyToManyField(to='recipes.Vedio'),
        ),
    ]
