# Generated by Django 3.2.11 on 2022-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220314_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.CharField(blank=True, default='0 Ratings', max_length=1000, null=True),
        ),
    ]
